package reports;

/**
 * Represents the different report types available in the Personal Finance
 * Manager (PFM) application.
 *
 * <p>
 * Each constant identifies a report that can be generated by the
 * ReportManager and selected through the ReportMenu.
 * </p>
 *
 * @author Alyssa Johnson
 * @author Sheikh Tanvir Hossain
 * @version 1.1
 * @since 1.0
 */
public enum ReportType {

    /**
     * Generates a complete financial report for a selected year.
     */
    ANNUAL("Annual Report"),

    /**
     * Generates a financial summary for a selected month.
     */
    MONTHLY("Monthly Summary"),

    /**
     * Generates yearly totals for each income and expense category.
     */
    CATEGORY_TOTALS("Category Totals"),

    /**
     * Generates an overall budget performance summary.
     */
    BUDGET_SUMMARY("Budget Summary");

    private final String displayName;

    ReportType(String displayName) {
        this.displayName = displayName;
    }

    /**
     * Gets the user-facing display name for this report type.
     *
     * @return display name for the report type
     */
    public String getDisplayName() {
        return displayName;
    }

    @Override
    public String toString() {
        return displayName;
    }
}
